### PR TITLE
Fix mouse click y offset

### PR DESCRIPTION
**Pull request by j3soon**
When clicking on the top particle space when scrolled, the newly created particle will be at the wrong spot.
Originally the particle will be created by the y value with respect to the viewport.
After this fix, the particle will be created by the y value with respect to the canvas.

### CODE REVIEW

**Comment by j3soon** [comment]
Currently this fix works when using `gulp` command on localhost. However it doesn't work on git pages...

**Comment by j3soon** [comment]
It now works on github pages. It seems like there are 2 particleJS config in this repo, `app.js` and `main.js`. I think the `gulp` command uses the `app.js` and github pages uses the `main.js` file.

**Comment by j3soon** [comment]
Hi, I really like this template, but I think this small bug isn't fixed yet.

The problem occurs when the user scrolls the page and start clicking their mouse. I've made a short GIF below for your reference. (The first one is the master branch, the second one is the code I wish to merge)

Basically the code only changes `"detect_on": "window"` to `"detect_on": "canvas"`, so I think merging this won't affect other functions.

scroll-bug

**Comment by nrandecker** [comment]
Yes, sorry I closed this by mistake I'm testing your changes now.

**Pull request merged**
