### PR TITLE
Fix build and vulnerabilities

### PR DESCRIPTION
**Pull request by fabienjuif**

### CODE REVIEW

**Comment by fabienjuif** [comment]
Yeah, on my project I changed the `const` to `var` so it passed

**Comment by fabienjuif** [comment]
@sconetto I fixed the JS in this PR.

About the CSS, you should change the `sass`, not the `css`.
I just tried to change the main color in `_vars.scss` and the application refreshed and print my new color (red). So I guess it works!

**Comment by nrandecker** [comment]
@fabienjuif Thanks for your work with the build issues. I haven't actively maintained this project in several months. Im testing your changes now will be adding them to the main repo shortly.

**Comment by fabienjuif** [comment]
@nrandecker You are welcome :) thank you for the merge ;)

**Pull request merged**
